# Generated by Django 4.2.7 on 2023-12-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilebook',
            name='transactionid',
        ),
    ]
