# Generated by Django 4.2.7 on 2023-12-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_profilebook_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilebook',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
