# Generated by Django 4.2.7 on 2023-12-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_borrowed_profilebook_borrowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed',
        ),
    ]
